In [1]:
import pandas as pd
import numpy as np
import matplotlib as mat
import seaborn as sns
import scipy, os, glob, re 
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

# use seaborn for plot defaults
# this can be safely commented out
import seaborn; seaborn.set()


In [2]:
from sklearn.linear_model import LinearRegression



In [25]:
data = pd.read_csv('./data.csv')
# 

mask_vec = ~np.isnan(data['func_dvars'])
clean_df = data[mask_vec]
mask_vec = ~np.isnan(data['func_mean_fd'])
data = clean_df[mask_vec]


/Users/suyashdb/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


In [26]:
X = data.iloc[:,2:-4]
X.shape
y = data.iloc[:,-3:-1] 
y_new = data.iloc[:,-1]
# print(y_new.value_counts(), y.iloc[:,0].value_counts())


cjv       cnr       efc         fber  fwhm_avg    fwhm_x    fwhm_y  \
0     0.383747  3.259968  0.609668   181.619858  3.944888  3.959924  4.039157   
1     0.574080  2.279440  0.606361   172.500031  3.992397  3.877495  4.173095   
2     0.314944  3.998569  0.577123   273.688171  4.016382  4.066009  4.092888   
3     0.418505  3.050534  0.571343   237.531143  3.601741  3.629409  3.627568   
4     0.286560  4.214082  0.550083   427.042389  3.808350  3.839143  3.841085   
5     0.435698  2.905045  0.603965   162.938904  3.926653  3.879666  4.077347   
6     0.382580  3.325713  0.578778   228.484604  3.912600  3.853066  3.999224   
7     0.441946  2.932388  0.598833   178.152893  3.702495  3.643685  3.814495   
8     0.329873  3.984281  0.545285   281.201416  3.778818  3.769009  3.830512   
9     0.450830  2.793116  0.623163   135.283371  3.619323  3.621857  3.660419   
10    0.396427  3.015634  0.612677   224.290771  3.901726  3.792238  4.029345   
11    0.336303  3.681724  0.582595   257.105225  3.616570  3.585266  3.652520   
12    0.430777  2.983890  0.572980   235.655823  3.680904  3.731638  3.635904   
13    0.458865  2.783876  0.622247   129.673035  3.735268  3.697781  3.720641   
14    0.388237  3.263390  0.599631   189.803207  3.943178  3.920962  3.949138   
15    0.618862  2.074819  0.626730   108.026299  3.813482  3.693952  4.012519   
16    0.422569  2.951146  0.630676   142.833725  3.985726  3.915847  4.133505   
17    0.576878  2.240916  0.612437   161.827972  3.745803  3.788171  3.819958   
18    0.374618  3.331780  0.596785   189.204315  3.916235  3.863000  4.023977   
19    0.313762  3.993368  0.565749   286.211548  3.800887  3.790809  3.840666   
20    0.348384  3.615115  0.585491   209.437607  3.845013  3.806314  3.874451   
21    0.415365  3.171044  0.546270   283.682129  4.171513  4.098695  4.302770   
22    0.446628  2.893461  0.603962   185.298477  3.824786  3.698924  3.969561   
23    0.352733  3.477461  0.553883   393.004761  3.651255  3.674724  3.649323   
24    0.326704  3.814190  0.576167   283.309570  3.885704  3.832695  3.994000   
25    0.349356  3.427086  0.601630   242.691589  3.696428  3.712609  3.689541   
26    0.348515  3.632659  0.549304   301.425964  4.006674  4.025800  4.037834   
27    0.367253  3.445695  0.566556   296.121796  3.714284  3.726428  3.747155   
28    0.431055  2.889399  0.590916   221.948624  4.064446  3.995666  4.160105   
29    0.360192  3.531252  0.577622   297.118805  3.870525  3.796990  3.937746   
...        ...       ...       ...          ...       ...       ...       ...   
1071  0.414187  3.049497  0.795972  1582.713989  3.226480  3.240240  3.334640   
1072  0.496697  2.661153  0.804697  1022.974792  3.194353  3.168850  3.310540   
1073  0.493061  2.645177  0.794798  2184.125000  3.283747  3.240520  3.430830   
1074  0.449789  2.873935  0.791124  1121.648926  3.016737  3.003160  3.128480   
1075  0.508724  2.623719  0.797319  2612.171387  3.215757  3.168240  3.389050   
1076  0.604568  2.154255  0.803885  1652.202148  3.202887  3.191690  3.406250   
1077  0.537413  2.497543  0.805906  1263.400146  3.059797  3.034480  3.244280   
1078  0.554580  2.441076  0.796388  1035.208252  3.149197  3.171620  3.373510   
1079  0.556315  2.430446  0.796125  1213.686768  3.384347  3.433740  3.443560   
1080  0.535971  2.474933  0.802109  2517.057617  3.151223  3.108030  3.412260   
1081  0.512558  2.546530  0.796531   906.293701  3.079457  3.088360  3.195800   
1082  0.487125  2.639577  0.787028  2875.933105  3.109603  3.073790  3.262180   
1083  0.686420  2.026522  0.794908  2746.939209  3.106877  3.105390  3.228240   
1084  0.485751  2.771382  0.795355  2784.411133  3.199460  3.134870  3.384690   
1085  0.432431  2.970917  0.794956  2146.377441  3.108097  3.067400  3.248720   
1086  0.539783  2.442216  0.797217  2207.468994  3.164650  3.081410  3.343060   
1087  0.500771  2.640999  0.802268   843.154175  3.196127  3.208430  3.349880   
1088  0.415361  3.156427  0.789127  2919.8

Converted rating for rows where both raters have rated into one column by random sampling

In [27]:
y = data.iloc[:,-3:-1] 
# y_new = data.iloc[:,-1]
import random
for index, row in y.iterrows():
    if row.isnull().any():
        print(row.sum())
        y_new.iloc[index,] = row.sum()
    else:
        y_new.iloc[index,] = random.choice(row)

1.0
-1.0
1.0
1.0
-1.0

/Users/suyashdb/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:549: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value



0.0
1.0
1.0
0.0
0.0
1.0
-1.0
1.0
-1.0
-1.0
1.0
0.0
1.0
0.0
-1.0
1.0
1.0
1.0
-1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
-1.0
0.0
1.0
0.0
0.0
0.0
0.0
-1.0
0.0
1.0
0.0
0.0
-1.0
1.0
0.0
1.0
0.0
1.0
1.0
-1.0
-1.0
1.0
0.0
0.0
0.0
1.0
-1.0
-1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
-1.0
1.0
1.0
1.0
0.0
-1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
1.0
0.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
0.0
0.0
-1.0
0.0
0.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
1.0
0.0
-1.0
-1.0
0.0
1.0
1.0
-1.0
0.0
1.0
1.0
0.0
0.0
1.0
-1.0
0.0
1.0
1.0
-1.0
0.0
-1.0
1.0
1.0
1.0
1.0
0.0
-1.0
1.0
1.0
1.0
0.0
1.0
1.0
-1.0
1.0
1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
1.0
-1.0
-1.0
-1.0
0.0
0.0
0.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0


IndexError: single positional indexer is out-of-bounds

In [30]:
y_new.shape, X.shape
# print(X_new.dtypes.value_counts())
# y_new.isnull()
# np.isnan(y_new.values).sum()


((1098,), (1098, 70))

### K Nearest neighbour 

In [31]:
# X, y = iris.data, iris.target
# from sklearn.linear_model import 

from sklearn.neighbors import KNeighborsClassifier
X_new = X.dropna()
clf = KNeighborsClassifier()
clf.fit(X_new.values, y_new)
# print(X_new.dtypes.value_counts())
# y_new.isnull()
# np.isnan(y_new.values).sum()

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [32]:
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X_new, y_new)
clf.fit(Xtrain, ytrain)
ypred = clf.predict(Xtest)
print(confusion_matrix(ytest, ypred))

[[44 19 14]
 [22 45 27]
 [31 27 46]]


/Users/suyashdb/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


### SGD


In [254]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split

X_new = X_new.dropna()
clf = SGDClassifier(loss= 'perceptron')
clf.fit(X_new.values, y_new)

Xtrain, Xtest, ytrain, ytest = train_test_split(X_new, y_new)
clf.fit(Xtrain, ytrain)
ypred = clf.predict(Xtest)
c = confusion_matrix(ytest, ypred, labels=[-1,0,1])
ypred = clf.predict(Xtest)
print(confusion_matrix(ytest, ypred))

[[ 10   0  66]
 [ 10   0  74]
 [  5   0 110]]


In [255]:
from pandas_ml import ConfusionMatrix
C = ConfusionMatrix(ytest, ypred)
C

Predicted  -1.0  0.0  1.0  __all__
Actual                            
-1.0          0    0   25       25
0.0           3    0   12       15
1.0           1    0   17       18
__all__       4    0   54       58

In [273]:
y_new.value_counts()

 1    418
 0    349
-1    331
Name: rater_3, dtype: int64