In [181]:
import pandas as pd
import numpy as np
import matplotlib as mat
import seaborn as sns
import scipy, os, glob, re 
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

# use seaborn for plot defaults
# this can be safely commented out
import seaborn; seaborn.set()


In [182]:
from sklearn.linear_model import LinearRegression



In [189]:
data = pd.read_csv('./abideIQM_DVARS_Labels.csv')
# 

mask_vec = ~np.isnan(X['func_dvars'])
clean_df = data[mask_vec]
mask_vec = ~np.isnan(X['func_mean_fd'])
data = clean_df[mask_vec]


/Users/suyashdb/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


In [201]:
X = data.iloc[:,2:-4]
X.shape
y = data.iloc[:,-3:-1] 
y_new = data.iloc[:,-1]
y_new

0       1
1      -1
2       1
3       1
4       0
5      -1
6       1
7       0
8       1
9       1
10      0
11      0
12      1
13     -1
14      1
15     -1
16     -1
17      1
18      0
19      1
20      1
21      0
22     -1
23      1
24      1
25      1
26      1
27     -1
28      1
29      1
       ..
1071    1
1072   -1
1073    0
1074    0
1075    0
1076   -1
1077   -1
1078    1
1079    0
1080    0
1081    0
1082   -1
1083    1
1084    0
1085    0
1086    0
1087    0
1088    0
1089    1
1090   -1
1091    0
1092    0
1093    0
1094    0
1095    0
1096    0
1097    0
1098   -1
1099    0
1100   -1
Name: rater_3, dtype: int64

Converted rating for rows where both raters have rated into one column by random sampling

In [202]:
# y = data.iloc[:,-3:-1] 
# y_new = data.iloc[:,-1]
import random
for index, row in y.iterrows():
    if row.isnull().any():
        print(row.sum())
        y_new.iloc[index,] = row.sum()
    else:
        y_new.iloc[index,] = random.choice(row)

1.0
-1.0
1.0
1.0
-1.0
0.0
1.0
1.0

/Users/suyashdb/anaconda/lib/python3.5/site-packages/pandas/core/indexing.py:549: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value



0.0
0.0
1.0
-1.0
1.0
-1.0
-1.0
1.0
0.0
1.0
0.0
-1.0
1.0
1.0
1.0
-1.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
-1.0
0.0
1.0
0.0
0.0
0.0
0.0
-1.0
0.0
1.0
0.0
0.0
-1.0
1.0
0.0
1.0
0.0
1.0
1.0
-1.0
-1.0
1.0
0.0
0.0
0.0
1.0
-1.0
-1.0
0.0
0.0
0.0
1.0
1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
-1.0
1.0
1.0
1.0
0.0
-1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
1.0
0.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
0.0
0.0
-1.0
0.0
0.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
1.0
0.0
-1.0
-1.0
0.0
1.0
1.0
-1.0
0.0
1.0
1.0
0.0
0.0
1.0
-1.0
0.0
1.0
1.0
-1.0
0.0
-1.0
1.0
1.0
1.0
1.0
0.0
-1.0
1.0
1.0
1.0
0.0
1.0
1.0
-1.0
1.0
1.0
1.0
1.0
1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
1.0
-1.0
-1.0
-1.0
0.0
0.0
0.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
-1.0
-1.0
-1.0
-1.0
-1.0
0.0
-1.0
0.0
0.0
-1.0

IndexError: single positional indexer is out-of-bounds

In [203]:
y_new.shape, X_new.shape
# print(X_new.dtypes.value_counts())
# y_new.isnull()
# np.isnan(y_new.values).sum()


((1098,), (1098, 70))

### K Nearest neighbour 

In [228]:
# X, y = iris.data, iris.target
# from sklearn.linear_model import 

from sklearn.neighbors import KNeighborsClassifier
X_new = X_new.dropna()
clf = KNeighborsClassifier()
clf.fit(X_new.values, y_new)
# print(X_new.dtypes.value_counts())
# y_new.isnull()
# np.isnan(y_new.values).sum()

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [229]:
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X_new, y_new)
clf.fit(Xtrain, ytrain)
ypred = clf.predict(Xtest)
print(confusion_matrix(ytest, ypred))

[[47 23 18]
 [31 26 24]
 [20 39 47]]


### SGD


In [254]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix
from sklearn.cross_validation import train_test_split

X_new = X_new.dropna()
clf = SGDClassifier(loss= 'perceptron')
clf.fit(X_new.values, y_new)

Xtrain, Xtest, ytrain, ytest = train_test_split(X_new, y_new)
clf.fit(Xtrain, ytrain)
ypred = clf.predict(Xtest)
c = confusion_matrix(ytest, ypred, labels=[-1,0,1])
ypred = clf.predict(Xtest)
print(confusion_matrix(ytest, ypred))

[[ 10   0  66]
 [ 10   0  74]
 [  5   0 110]]


In [255]:
from pandas_ml import ConfusionMatrix
C = ConfusionMatrix(ytest, ypred)
C

Predicted  -1.0  0.0  1.0  __all__
Actual                            
-1.0          0    0   25       25
0.0           3    0   12       15
1.0           1    0   17       18
__all__       4    0   54       58

In [273]:
y_new.value_counts()

 1    418
 0    349
-1    331
Name: rater_3, dtype: int64